### ISSUE TITLE
`ft_dplyr_transformer()` does not work with sampled data in Spark 4.0.1

### ISSUE THREAD

**Issue by edgararuiz** [rstudio/sparklyr#3504]
reprex:

``` r
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter
sc <- spark_connect("local", version = "4.0.1")

tbl_mtcars <- copy_to(sc, mtcars)

sampled <- tbl_mtcars |> 
  dplyr::sample_n(10) 
  
tbl_mtcars |> 
  ft_dplyr_transformer(sampled)
#> Error:
#> ! java.lang.NoSuchMethodError: 'void
#>   org.apache.spark.ml.param.Param.<init>(org.apache.spark.ml.util.Identifiable,
#>   java.lang.String, java.lang.String, scala.reflect.ClassTag)'
#> 
#> Run ]8;;x-r-run:sparklyr::spark_last_error()`sparklyr::spark_last_error()`]8;; to see the full Spark error (multiple lines)
#> To use the previous style of error message set
#> `options("sparklyr.simple.errors" = TRUE)`

spark_disconnect(sc)
```

<sup>Created on 2025-10-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
